######################## default configuration ####################
baseURL = "https://heribertorangel.com"
languageCode = "en-us"
title = "Heriberto R."
theme = "influencer-hugo"
summaryLength = "20"
paginate = 6

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Book"
  URL = "book"
  weight = 1
  
  [[menu.main]]
  name = "Chapter"
  URL = "chapter"
  weight = 2
  
  [[menu.main]]
  name = "Author"
  URL = "author"
  weight = 3
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 4
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/hrangelogo.png"
home = "Home"
# Meta data
description = "This is my home page"
author = "Beto R."
# Google Analitycs
googleAnalitycsID = "UA-136830935-1"
# copyright
copyright = "Copyright &copy; 2023 [H. Rangel](https://gethugothemes.com) "

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# Footer ########################
[params.footer]
content = "Hi, Yes I do have keratoconus."

############################# post share ###################
[[params.share]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook/heribertorm/"

[[params.share]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/hrangelma/"

[[params.share]]
title = "reddit"
icon = "ti-reddit" # themify icon : https://themify.me/themify-icons
link = "#"